services:
  db:
    image: mysql:latest
    container_name: universidade-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: universidade
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
volumes:
  db_data:
    driver: local